baseurl: http://blog.liuxizong.com
permalink: /:year/:month/:day/:title
pygments: true
date_format: "ordinal"
subscribe_rss: /atom.xml
markdown: redcarpet
redcarpet:
  extensions: 
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
